### ISSUE TITLE
Record start sound plays late and is heard in the recording

### ISSUE THREAD

**Issue by jorgeluiscarrillo** [adocilesloth/SRBeep#10]
I built your plugin on Fedora Linux and using latest OBS version 26.0.2. It seems like the start sound is playing after I press start recording in OBS so the sound is heard at the start of every recording. The stop recording sound works fine and is not heard in the video.

**Comment by adocilesloth** [comment]
Read this post from four years ago.

https://obsproject.com/forum/threads/stream-recording-start-stop-beep-srbeep.48058/post-233596
