### ISSUE TITLE
Replay Buffer Save Sound Effect

### ISSUE THREAD

**Issue by HavoxYT** [adocilesloth/SRBeep#11]
I just wanted to know if there was a way to make a sound play when saving the replay buffer or if that could be added at some point. I see the project has been somewhat abandoned recently but it's a feature I've been looking around for

**Comment by JoshyClicks** [comment]
Im waiting for this

**Comment by snakecase** [comment]
+1

**Comment by adocilesloth** [comment]
I have no plans to add this
