### ISSUE TITLE
Suggestion for an Makefile update

### ISSUE THREAD

**Issue by aznlir88** [adocilesloth/SRBeep#15]
Hello, I am no coder or anything but I totally do not understand that part of the Makefile:
```

ifndef FFmpegPath
FFmpegPath = $(HOME)/ffmpeg_sources/ffmpeg
endif
ifndef FFmpegLib
FFmpegLib = $(HOME)/ffmpeg_build/lib
endif
ifndef SDL_INCLUDE
SDL_INCLUDE = $(HOME)/SDL2-2.0.10/include
endif
ifndef SDL_LIB
SDL_LIB = $(HOME)/SDL2-2.0.10/build
endif
```
I mean why does it look in user's home directory? In my case it did not see SDL.h unless I changed the SDL part to:
```

ifndef SDL_INCLUDE
SDL_INCLUDE = /usr/include/SDL2
endif
```
So just passing the suggestion for an update.

**Comment by adocilesloth** [comment]
Took a while but Makefile is updated.
