### ISSUE TITLE
SRBeep has stoped working since latest update it OBS, WIN VERSION 28.0.1

### ISSUE THREAD

**Issue by PSYKO-nz** [adocilesloth/SRBeep#16]
Hey mate, first off thank you for this epic little mod, I use it everyday and have done for years, however it stopped working since I installed the latest version of OBS 28.0.1, a few other mods have also stopped so it's not just this one,

I tried a complete reinstall of SRBeep and that didn't fix it

I'm hoping you are able to get it working again cause SRBeep is the reason I decided to use obs hahaha

Thanks dude!

**Comment by RemixPL1994** [comment]
May this plugin be updated. I can't imagine using OBS without SRBeep :/

**Comment by Slegnor** [comment]
Can confirm OBS 28 update has stopped the plugin working

**Comment by eebssk1** [comment]
@adocilesloth pls Re-link the module with latest library from 28

**Comment by eebssk1** [comment]
@PSYKO-nz @RemixPL1994 @Slegnor 
In the meantime, you guys can hex edit the binary and modify the av support lib name to the one used by obs in the import table.
It's simple,just search the old lib name use hex editors and replace the final bit(version code) to the one in obs.
You can verify the result using peviewer in processhacker.

**Comment by adocilesloth** [comment]
> @adocilesloth pls Re-link the module with latest library from 28

Or someone can post a log as I have asked on the forum as I have no problems with the plugin as is with OBS 28 and would like to get a better idea of what the problem is.

**Comment by eebssk1** [comment]
> > @adocilesloth pls Re-link the module with latest library from 28
> 
> Or someone can post a log as I have asked on the forum as I have no problems with the plugin as is with OBS 28 and would like to get a better idea of what the problem is.

After fixing the import table. The module loads successfully. But I got "SRBEEP: play_clip: SDL_OpenAudio failed" in obs log when start/stop recording. I currently don't have any idea on this even since the related code seems straightforward..

**Comment by eebssk1** [comment]
> > > @adocilesloth pls Re-link the module with latest library from 28
> > 
> > 
> > Or someone can post a log as I have asked on the forum as I have no problems with the plugin as is with OBS 28 and would like to get a better idea of what the problem is.
> 
> After fixing the import table. The module loads successfully. But I got "SRBEEP: play_clip: SDL_OpenAudio failed" in obs log when start/stop recording. I currently don't have any idea on this even since the related code seems straightforward..

I took some time to recompile it with latest dependency from OBS and SDL2, and now it works correctly.
No code changes are required, just recompile.
(Some code is deprecated when compile,just ignore them with compiler flags)

**Comment by eebssk1** [comment]
[Link updated][Recompiled with Clang64 it's smaller and no distort sound]
This is my compiled version. Should work without problem.
https://file.io/wM9Re8sVvHHv

FAQ:
Q0.Why is this such larger than the original one?
A0.It's compiled with mingw(ucrt) gcc and has some mingw components statically linked.
Q1.Embbed signature not trusted?
A1.This is normal. However if it says signature does not match any file or is invalid then the file is very probably broken.

**Comment by RemixPL1994** [comment]
@eebssk1 

I wanted to download it and try it out, but the link doesn't work anymore.

**Comment by eebssk1** [comment]
> @eebssk1
> 
> I wanted to download it and try it out, but the link doesn't work anymore.

https://tmpfiles.org/dl/163088/srbeep.dll
https://filebin.net/ds4qknwhpclojygs

**Comment by Tonycubed2** [comment]
@360758
This may be trying your patience, but hoping for a fresh working link?  All links above do not work any longer...

**Comment by eebssk1** [comment]
> @360758 This may be trying your patience, but hoping for a fresh working link? All links above do not work any longer...

Try this link
https://sh2.godaftwithebk.pub/nextcloud/s/8aRgcLQCadHwFXt
Should work as long as I don't mess up my cloud server and/or forget to pay the rent.LOL

**Comment by Tonycubed2** [comment]
Thank you!!!!!!! And it works now!  I am so confused.  Why is this working version not repalcing the 2019 posted one?  I take it thsi is your own modded version?  But no matter what, a million thanks.

**Comment by adocilesloth** [comment]
Fixed the problems. Would be nice if next time someone actually posts a log and doesn't assume "there is nothing in there"
https://github.com/adocilesloth/SRBeep/releases/tag/OBS28

**Comment by RemixPL1994** [comment]
@adocilesloth @eebssk1

Hello. In fact, from what I've checked and tested, SRBeep v2.1.1 works fine up to OBS Studio v29.0.2.

However, with the first OBS-Studio-29.1 beta 1, it stops working.

Is it possible to re-edit the files and update it to make it work again?
