### ISSUE TITLE
How to build in windows

### ISSUE THREAD

**Issue by bilogic** [adocilesloth/SRBeep#4]
Hi,

Would you be kind enough to explain how I can build this in Windows? Thank you.

**Comment by adocilesloth** [comment]
The dependencies are the same as for Linux/Mac (OBS, ffmpeg, SDL2). Add the necessary include PATHs for OBS, ffmpeg and SDL2 and link to the following libraries:
obs-frontend-api.lib
avutil.lib
SDL2.lib
swresample.lib
avformat.lib
avcodec.lib
obs.lib

You should then be good to go.

**Comment by bilogic** [comment]
Right thanks. But what is the tool used to process the makefile?

**Comment by adocilesloth** [comment]
I don't know. I built it in Visual Studio 2015 so I've never actually used the makefile on windows.

**Comment by bilogic** [comment]
I see. Do you start it as MFC DLL or...? I asked as there are no project files in this repo.

**Comment by adocilesloth** [comment]
It's just a DLL, no MFC or ATL. You do not need the header files for MFC or ATL for it to work.

**Comment by bilogic** [comment]
I have obs-frontend-api.lib in my linker's path but still face this... any help is greatly appreciated. Thank you.
```
error LNK2019: unresolved external symbol _obs_frontend_add_event_callback referenced in function _obs_module_load
error LNK2019: unresolved external symbol _obs_get_module_data_path referenced in function "void __cdecl start_stream_sound(void)" (?start_stream_sound@@YAXXZ)
```

**Comment by adocilesloth** [comment]
I'm not sure. I'd guess it might be obs.lib missing but I don't know. Sorry.

Although if obs.lib is missing, I'd imagine there would me more missing externals...

It's been awhile since I've complied a plugin for OBS, so I can't remember.

**Comment by Tinker-Terry** [comment]
Would you be kind enough to explain fully how to install this plug-in in windows ten. The readme says to drag the OBS folder into program files and the OBS folder is already in program files. I downloaded the zip file and there is no OBS folder in it. So what exactly should I be dragging where?
