### ISSUE TITLE
Not work any more on OBS v24

### ISSUE THREAD

**Issue by eebssk1** [adocilesloth/SRBeep#5]
This plugin is not working with OBS v24.0.1
I found it the plugin requires old ffmpeg,so I use PE Tools to change dll dependency to the new ffmpeg used by OBS.Then the plugin load normally but the sound won't play.

**Comment by adocilesloth** [comment]
It's working fine for me. What OS are you running and 32bit or 64bit version of OBS?

**Comment by eebssk1** [comment]
> 
> 
> It's working fine for me. What OS are you running and 32bit or 64bit version of OBS?

Win10 1903
V24.0.1 X64

**Comment by eebssk1** [comment]
I downloaded the plugin from OBS official site.

**Comment by adocilesloth** [comment]
Not sure what to suggest then. It works fine for me with the same OS and OBS version so I can't really trouble shoot it.

If the plugin is loading but it's not playing sound, make sure the four .mp3 files are in C:/Program Files (x86)/obs-studio/data/obs-plugins/SRBeep (it may be C:/Program Files/obs-... I can't remember how OBS installs)

**Comment by eebssk1** [comment]
> 
> 
> Not sure what to suggest then. It works fine for me with the same OS and OBS version so I can't really trouble shoot it.
> 
> If the plugin is loading but it's not playing sound, make sure the four .mp3 files are in C:/Program Files (x86)/obs-studio/data/obs-plugins/SRBeep (it may be C:/Program Files/obs-... I can't remember how OBS installs)

It may because you have both old and new ffmpeg libraries installed.The plugin is trying to load the old one.I used the dependency walker and found the plugin try to load ffmpeg 57.OBS now uses ffmpeg 58.You may want to look into  my PR.It solved the problem for me.(looks like VS reformatted the code...)

**Comment by eebssk1** [comment]
And yes you need to rebuild the plugin with new ffmpeg for windows with that PR.

**Comment by adocilesloth** [comment]
When I get a chance, I'll build and check the PR

**Comment by adocilesloth** [comment]
I've been a bit rude and updated the code without checking your PR. Would you be able to check the updated plugin I've just released? I'm curious if it works after a rebuild against the newer FFMPEG and SDL2.

My tests on linux were resulting in silence too and the rebuild seems to have fixed that. If it still doesn't work, I'll merge and properly test your PR (and remember how to fix conflicts).

**Comment by eebssk1** [comment]
Yes,it works on windows too.
So..Your are still using the deprecated API,this works fine at this time.But if FFMpeg Team decide to compeletely delete them(And OBS follows up too),then you need to fix it again.
Github didn't detect any conflicts,so the PR should still work.
Well,for the API change,you check the Changelog.FFmpeg just want to rework some api since they entered a new generation.

**Comment by adocilesloth** [comment]
Yeah, you are probably correct, but at least it works. Thanks for checking.

I'll merge the PR at some point to update the FFMPEG API.
