### ISSUE TITLE
Proposition

### ISSUE THREAD

**Issue by gitalexhubuser** [adocilesloth/SRBeep#8]

**Comment by gitalexhubuser** [comment]
is it possible to modify a little bit this plugin. and pause the record until silence is detected.
and continue recording when dB level is too high?

**Comment by adocilesloth** [comment]
I'm not entirely sure what you are asking for but I am sure the answer is no.  It boils down to the fast that, as far as I know, you cannot monitor the audio via OBS's API. This may have changed as I have admittedly not been keeping up with what is and isn't accessible. 

If you were wanting the plugin the play the sound but not start recording until some other sound is detected, this would require a ground up re-write of the plugin which is not going to happen. If the intention is to not record the first "beep", see this [post in the OBS forum](https://obsproject.com/forum/threads/stream-recording-start-stop-beep-srbeep.48058/page-2#post-233596).

If you want the plugin to pause recordings when there is no sound and resume when there is, regardless of when the sound occurs, that is _well_ out of scope for this plugin. That would be a different plugin as this one is only concerned with playing sounds when streaming/recording starts/stops/pauses.
